/**
 * Note: This license has also been called the “Simplified BSD License” and the “FreeBSD License”.
 *
 * Copyright 2024 MESE POC: Volker Voß, Federal Armed Forces of Germany
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted
 * provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of
 * conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of
 * conditions and the following disclaimer in the documentation and/or other materials provided with
 * the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSEnARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BEn LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 */
package de.bundeswehr.mese.sedapexpress.protobuf;

import com.google.protobuf.AbstractMessageLite;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: sedapexpress.proto
//Protobuf Java Version: 4.27.3

public final class ProtobufMessage {
    private ProtobufMessage() {
    }

    static {
	com.google.protobuf.RuntimeVersion
		.validateProtobufGencodeVersion(
						com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
						/* major= */ 4,
						/* minor= */ 26,
						/* patch= */ 1,
						/* suffix= */ "",
						ProtobufMessage.class.getName());
    }

    public static void registerAllExtensions(
	    com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
	    com.google.protobuf.ExtensionRegistry registry) {
	ProtobufMessage
		.registerAllExtensions(
				       (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface SomeMessageOrBuilder extends
	    // @@protoc_insertion_point(interface_extends:SomeMessage)
	    com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>repeated .SomeMessage.Messages messages = 1;</code>
	 */
	java.util.List<ProtobufMessage.SomeMessage.Messages> getMessagesList();

	/**
	 * <code>repeated .SomeMessage.Messages messages = 1;</code>
	 */
	ProtobufMessage.SomeMessage.Messages getMessages(int index);

	/**
	 * <code>repeated .SomeMessage.Messages messages = 1;</code>
	 */
	int getMessagesCount();

	/**
	 * <code>repeated .SomeMessage.Messages messages = 1;</code>
	 */
	java.util.List<? extends ProtobufMessage.SomeMessage.MessagesOrBuilder> getMessagesOrBuilderList();

	/**
	 * <code>repeated .SomeMessage.Messages messages = 1;</code>
	 */
	ProtobufMessage.SomeMessage.MessagesOrBuilder getMessagesOrBuilder(
		int index);
    }

    /**
     * Protobuf type {@code SomeMessage}
     */
    public static final class SomeMessage extends
	    com.google.protobuf.GeneratedMessage implements
	    // @@protoc_insertion_point(message_implements:SomeMessage)
	    SomeMessageOrBuilder {
	private static final long serialVersionUID = 0L;
	static {
	    com.google.protobuf.RuntimeVersion
		    .validateProtobufGencodeVersion(
						    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
						    /* major= */ 4,
						    /* minor= */ 26,
						    /* patch= */ 1,
						    /* suffix= */ "",
						    SomeMessage.class.getName());
	}

	// Use SomeMessage.newBuilder() to construct.
	private SomeMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
	    super(builder);
	}

	private SomeMessage() {
	    this.messages_ = java.util.Collections.emptyList();
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
	    return ProtobufMessage.internal_static_SomeMessage_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
	    return ProtobufMessage.internal_static_SomeMessage_fieldAccessorTable
		    .ensureFieldAccessorsInitialized(
						     ProtobufMessage.SomeMessage.class,
						     ProtobufMessage.SomeMessage.Builder.class);
	}

	public interface MessagesOrBuilder extends
		// @@protoc_insertion_point(interface_extends:SomeMessage.Messages)
		com.google.protobuf.MessageOrBuilder {

	    /**
	     * <code>string message = 1;</code>
	     *
	     * @return The message.
	     */
	    java.lang.String getMessage();

	    /**
	     * <code>string message = 1;</code>
	     *
	     * @return The bytes for message.
	     */
	    com.google.protobuf.ByteString getMessageBytes();
	}

	/**
	 * Protobuf type {@code SomeMessage.Messages}
	 */
	public static final class Messages extends
		com.google.protobuf.GeneratedMessage implements
		// @@protoc_insertion_point(message_implements:SomeMessage.Messages)
		MessagesOrBuilder {
	    private static final long serialVersionUID = 0L;
	    static {
		com.google.protobuf.RuntimeVersion
			.validateProtobufGencodeVersion(
							com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
							/* major= */ 4,
							/* minor= */ 26,
							/* patch= */ 1,
							/* suffix= */ "",
							Messages.class.getName());
	    }

	    // Use Messages.newBuilder() to construct.
	    private Messages(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
		super(builder);
	    }

	    private Messages() {
		this.message_ = "";
	    }

	    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return ProtobufMessage.internal_static_SomeMessage_Messages_descriptor;
	    }

	    @java.lang.Override
	    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
		return ProtobufMessage.internal_static_SomeMessage_Messages_fieldAccessorTable
			.ensureFieldAccessorsInitialized(
							 ProtobufMessage.SomeMessage.Messages.class,
							 ProtobufMessage.SomeMessage.Messages.Builder.class);
	    }

	    public static final int MESSAGE_FIELD_NUMBER = 1;
	    private volatile java.lang.Object message_ = "";

	    /**
	     * <code>string message = 1;</code>
	     *
	     * @return The message.
	     */
	    @java.lang.Override
	    public java.lang.String getMessage() {
		java.lang.Object ref = this.message_;
		if (ref instanceof java.lang.String) {
		    return (java.lang.String) ref;
		} else {
		    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
		    java.lang.String s = bs.toStringUtf8();
		    this.message_ = s;
		    return s;
		}
	    }

	    /**
	     * <code>string message = 1;</code>
	     *
	     * @return The bytes for message.
	     */
	    @java.lang.Override
	    public com.google.protobuf.ByteString getMessageBytes() {
		java.lang.Object ref = this.message_;
		if (ref instanceof java.lang.String) {
		    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
			    .copyFromUtf8(
					  (java.lang.String) ref);
		    this.message_ = b;
		    return b;
		} else {
		    return (com.google.protobuf.ByteString) ref;
		}
	    }

	    private byte memoizedIsInitialized = -1;

	    @java.lang.Override
	    public final boolean isInitialized() {
		byte isInitialized = this.memoizedIsInitialized;
		if (isInitialized == 1) {
		    return true;
		}
		if (isInitialized == 0) {
		    return false;
		}

		this.memoizedIsInitialized = 1;
		return true;
	    }

	    @java.lang.Override
	    public void writeTo(com.google.protobuf.CodedOutputStream output)
		    throws java.io.IOException {
		if (!com.google.protobuf.GeneratedMessage.isStringEmpty(this.message_)) {
		    com.google.protobuf.GeneratedMessage.writeString(output, 1, this.message_);
		}
		getUnknownFields().writeTo(output);
	    }

	    @java.lang.Override
	    public int getSerializedSize() {
		int size = this.memoizedSize;
		if (size != -1) {
		    return size;
		}

		size = 0;
		if (!com.google.protobuf.GeneratedMessage.isStringEmpty(this.message_)) {
		    size += com.google.protobuf.GeneratedMessage.computeStringSize(1, this.message_);
		}
		size += getUnknownFields().getSerializedSize();
		this.memoizedSize = size;
		return size;
	    }

	    @java.lang.Override
	    public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
		    return true;
		}
		if (!(obj instanceof ProtobufMessage.SomeMessage.Messages other)) {
		    return super.equals(obj);
		}
		if (!getMessage()
			.equals(other.getMessage())) {
		    return false;
		}
		if (!getUnknownFields().equals(other.getUnknownFields())) {
		    return false;
		}
		return true;
	    }

	    @java.lang.Override
	    public int hashCode() {
		if (this.memoizedHashCode != 0) {
		    return this.memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + Messages.getDescriptor().hashCode();
		hash = (37 * hash) + Messages.MESSAGE_FIELD_NUMBER;
		hash = (53 * hash) + getMessage().hashCode();
		hash = (29 * hash) + getUnknownFields().hashCode();
		this.memoizedHashCode = hash;
		return hash;
	    }

	    public static ProtobufMessage.SomeMessage.Messages parseFrom(
		    java.nio.ByteBuffer data)
		    throws com.google.protobuf.InvalidProtocolBufferException {
		return Messages.PARSER.parseFrom(data);
	    }

	    public static ProtobufMessage.SomeMessage.Messages parseFrom(
		    java.nio.ByteBuffer data,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
		return Messages.PARSER.parseFrom(data, extensionRegistry);
	    }

	    public static ProtobufMessage.SomeMessage.Messages parseFrom(
		    com.google.protobuf.ByteString data)
		    throws com.google.protobuf.InvalidProtocolBufferException {
		return Messages.PARSER.parseFrom(data);
	    }

	    public static ProtobufMessage.SomeMessage.Messages parseFrom(
		    com.google.protobuf.ByteString data,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
		return Messages.PARSER.parseFrom(data, extensionRegistry);
	    }

	    public static ProtobufMessage.SomeMessage.Messages parseFrom(byte[] data)
		    throws com.google.protobuf.InvalidProtocolBufferException {
		return Messages.PARSER.parseFrom(data);
	    }

	    public static ProtobufMessage.SomeMessage.Messages parseFrom(
		    byte[] data,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
		return Messages.PARSER.parseFrom(data, extensionRegistry);
	    }

	    public static ProtobufMessage.SomeMessage.Messages parseFrom(java.io.InputStream input)
		    throws java.io.IOException {
		return com.google.protobuf.GeneratedMessage
			.parseWithIOException(Messages.PARSER, input);
	    }

	    public static ProtobufMessage.SomeMessage.Messages parseFrom(
		    java.io.InputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
		return com.google.protobuf.GeneratedMessage
			.parseWithIOException(Messages.PARSER, input, extensionRegistry);
	    }

	    public static ProtobufMessage.SomeMessage.Messages parseDelimitedFrom(java.io.InputStream input)
		    throws java.io.IOException {
		return com.google.protobuf.GeneratedMessage
			.parseDelimitedWithIOException(Messages.PARSER, input);
	    }

	    public static ProtobufMessage.SomeMessage.Messages parseDelimitedFrom(
		    java.io.InputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
		return com.google.protobuf.GeneratedMessage
			.parseDelimitedWithIOException(Messages.PARSER, input, extensionRegistry);
	    }

	    public static ProtobufMessage.SomeMessage.Messages parseFrom(
		    com.google.protobuf.CodedInputStream input)
		    throws java.io.IOException {
		return com.google.protobuf.GeneratedMessage
			.parseWithIOException(Messages.PARSER, input);
	    }

	    public static ProtobufMessage.SomeMessage.Messages parseFrom(
		    com.google.protobuf.CodedInputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
		return com.google.protobuf.GeneratedMessage
			.parseWithIOException(Messages.PARSER, input, extensionRegistry);
	    }

	    @java.lang.Override
	    public Builder newBuilderForType() {
		return Messages.newBuilder();
	    }

	    public static Builder newBuilder() {
		return Messages.DEFAULT_INSTANCE.toBuilder();
	    }

	    public static Builder newBuilder(ProtobufMessage.SomeMessage.Messages prototype) {
		return Messages.DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	    }

	    @java.lang.Override
	    public Builder toBuilder() {
		return this == Messages.DEFAULT_INSTANCE
			? new Builder()
			: new Builder().mergeFrom(this);
	    }

	    @java.lang.Override
	    protected Builder newBuilderForType(
		    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	    }

	    /**
	     * Protobuf type {@code SomeMessage.Messages}
	     */
	    public static final class Builder extends
		    com.google.protobuf.GeneratedMessage.Builder<Builder> implements
		    // @@protoc_insertion_point(builder_implements:SomeMessage.Messages)
		    ProtobufMessage.SomeMessage.MessagesOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		    return ProtobufMessage.internal_static_SomeMessage_Messages_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
		    return ProtobufMessage.internal_static_SomeMessage_Messages_fieldAccessorTable
			    .ensureFieldAccessorsInitialized(
							     ProtobufMessage.SomeMessage.Messages.class,
							     ProtobufMessage.SomeMessage.Messages.Builder.class);
		}

		// Construct using Sedapexpress.SomeMessage.Messages.newBuilder()
		private Builder() {

		}

		private Builder(
			com.google.protobuf.GeneratedMessage.BuilderParent parent) {
		    super(parent);

		}

		@java.lang.Override
		public Builder clear() {
		    super.clear();
		    this.bitField0_ = 0;
		    this.message_ = "";
		    return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
		    return ProtobufMessage.internal_static_SomeMessage_Messages_descriptor;
		}

		@java.lang.Override
		public ProtobufMessage.SomeMessage.Messages getDefaultInstanceForType() {
		    return ProtobufMessage.SomeMessage.Messages.getDefaultInstance();
		}

		@java.lang.Override
		public ProtobufMessage.SomeMessage.Messages build() {
		    ProtobufMessage.SomeMessage.Messages result = buildPartial();
		    if (!result.isInitialized()) {
			throw Builder.newUninitializedMessageException(result);
		    }
		    return result;
		}

		@java.lang.Override
		public ProtobufMessage.SomeMessage.Messages buildPartial() {
		    ProtobufMessage.SomeMessage.Messages result = new ProtobufMessage.SomeMessage.Messages(this);
		    if (this.bitField0_ != 0) {
			buildPartial0(result);
		    }
		    onBuilt();
		    return result;
		}

		private void buildPartial0(ProtobufMessage.SomeMessage.Messages result) {
		    int from_bitField0_ = this.bitField0_;
		    if (((from_bitField0_ & 0x00000001) != 0)) {
			result.message_ = this.message_;
		    }
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
		    if (other instanceof ProtobufMessage.SomeMessage.Messages) {
			return mergeFrom((ProtobufMessage.SomeMessage.Messages) other);
		    } else {
			super.mergeFrom(other);
			return this;
		    }
		}

		public Builder mergeFrom(ProtobufMessage.SomeMessage.Messages other) {
		    if (other == ProtobufMessage.SomeMessage.Messages.getDefaultInstance()) {
			return this;
		    }
		    if (!other.getMessage().isEmpty()) {
			this.message_ = other.message_;
			this.bitField0_ |= 0x00000001;
			onChanged();
		    }
		    this.mergeUnknownFields(other.getUnknownFields());
		    onChanged();
		    return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
		    return true;
		}

		@java.lang.Override
		public Builder mergeFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		    if (extensionRegistry == null) {
			throw new java.lang.NullPointerException();
		    }
		    try {
			boolean done = false;
			while (!done) {
			    int tag = input.readTag();
			    switch (tag) {
			    case 0:
				done = true;
				break;
			    case 10: {
				this.message_ = input.readStringRequireUtf8();
				this.bitField0_ |= 0x00000001;
				break;
			    } // case 10
			    default: {
				if (!super.parseUnknownField(input, extensionRegistry, tag)) {
				    done = true; // was an endgroup tag
				}
				break;
			    } // default:
			    } // switch (tag)
			} // while (!done)
		    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw e.unwrapIOException();
		    } finally {
			onChanged();
		    } // finally
		    return this;
		}

		private int bitField0_;

		private java.lang.Object message_ = "";

		/**
		 * <code>string message = 1;</code>
		 *
		 * @return The message.
		 */
		public java.lang.String getMessage() {
		    java.lang.Object ref = this.message_;
		    if (!(ref instanceof java.lang.String)) {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			this.message_ = s;
			return s;
		    } else {
			return (java.lang.String) ref;
		    }
		}

		/**
		 * <code>string message = 1;</code>
		 *
		 * @return The bytes for message.
		 */
		public com.google.protobuf.ByteString getMessageBytes() {
		    java.lang.Object ref = this.message_;
		    if (ref instanceof String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString
				.copyFromUtf8(
					      (java.lang.String) ref);
			this.message_ = b;
			return b;
		    } else {
			return (com.google.protobuf.ByteString) ref;
		    }
		}

		/**
		 * <code>string message = 1;</code>
		 *
		 * @param value The message to set.
		 * @return This builder for chaining.
		 */
		public Builder setMessage(
			java.lang.String value) {
		    if (value == null) {
			throw new NullPointerException();
		    }
		    this.message_ = value;
		    this.bitField0_ |= 0x00000001;
		    onChanged();
		    return this;
		}

		/**
		 * <code>string message = 1;</code>
		 *
		 * @return This builder for chaining.
		 */
		public Builder clearMessage() {
		    this.message_ = Messages.getDefaultInstance().getMessage();
		    this.bitField0_ = (this.bitField0_ & ~0x00000001);
		    onChanged();
		    return this;
		}

		/**
		 * <code>string message = 1;</code>
		 *
		 * @param value The bytes for message to set.
		 * @return This builder for chaining.
		 */
		public Builder setMessageBytes(
			com.google.protobuf.ByteString value) {
		    if (value == null) {
			throw new NullPointerException();
		    }
		    AbstractMessageLite.checkByteStringIsUtf8(value);
		    this.message_ = value;
		    this.bitField0_ |= 0x00000001;
		    onChanged();
		    return this;
		}

		// @@protoc_insertion_point(builder_scope:SomeMessage.Messages)
	    }

	    // @@protoc_insertion_point(class_scope:SomeMessage.Messages)
	    private static final ProtobufMessage.SomeMessage.Messages DEFAULT_INSTANCE;
	    static {
		DEFAULT_INSTANCE = new ProtobufMessage.SomeMessage.Messages();
	    }

	    public static ProtobufMessage.SomeMessage.Messages getDefaultInstance() {
		return Messages.DEFAULT_INSTANCE;
	    }

	    private static final com.google.protobuf.Parser<Messages> PARSER = new com.google.protobuf.AbstractParser<Messages>() {
		@java.lang.Override
		public Messages parsePartialFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		    Builder builder = Messages.newBuilder();
		    try {
			builder.mergeFrom(input, extensionRegistry);
		    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw e.setUnfinishedMessage(builder.buildPartial());
		    } catch (com.google.protobuf.UninitializedMessageException e) {
			throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
		    } catch (java.io.IOException e) {
			throw new com.google.protobuf.InvalidProtocolBufferException(e)
				.setUnfinishedMessage(builder.buildPartial());
		    }
		    return builder.buildPartial();
		}
	    };

	    public static com.google.protobuf.Parser<Messages> parser() {
		return Messages.PARSER;
	    }

	    @java.lang.Override
	    public com.google.protobuf.Parser<Messages> getParserForType() {
		return Messages.PARSER;
	    }

	    @java.lang.Override
	    public ProtobufMessage.SomeMessage.Messages getDefaultInstanceForType() {
		return Messages.DEFAULT_INSTANCE;
	    }

	}

	public static final int MESSAGES_FIELD_NUMBER = 1;
	private java.util.List<ProtobufMessage.SomeMessage.Messages> messages_;

	/**
	 * <code>repeated .SomeMessage.Messages messages = 1;</code>
	 */
	@java.lang.Override
	public java.util.List<ProtobufMessage.SomeMessage.Messages> getMessagesList() {
	    return this.messages_;
	}

	/**
	 * <code>repeated .SomeMessage.Messages messages = 1;</code>
	 */
	@java.lang.Override
	public java.util.List<? extends ProtobufMessage.SomeMessage.MessagesOrBuilder> getMessagesOrBuilderList() {
	    return this.messages_;
	}

	/**
	 * <code>repeated .SomeMessage.Messages messages = 1;</code>
	 */
	@java.lang.Override
	public int getMessagesCount() {
	    return this.messages_.size();
	}

	/**
	 * <code>repeated .SomeMessage.Messages messages = 1;</code>
	 */
	@java.lang.Override
	public ProtobufMessage.SomeMessage.Messages getMessages(int index) {
	    return this.messages_.get(index);
	}

	/**
	 * <code>repeated .SomeMessage.Messages messages = 1;</code>
	 */
	@java.lang.Override
	public ProtobufMessage.SomeMessage.MessagesOrBuilder getMessagesOrBuilder(
		int index) {
	    return this.messages_.get(index);
	}

	private byte memoizedIsInitialized = -1;

	@java.lang.Override
	public final boolean isInitialized() {
	    byte isInitialized = this.memoizedIsInitialized;
	    if (isInitialized == 1) {
		return true;
	    }
	    if (isInitialized == 0) {
		return false;
	    }

	    this.memoizedIsInitialized = 1;
	    return true;
	}

	@java.lang.Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
		throws java.io.IOException {
	    for (int i = 0; i < this.messages_.size(); i++) {
		output.writeMessage(1, this.messages_.get(i));
	    }
	    getUnknownFields().writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
	    int size = this.memoizedSize;
	    if (size != -1) {
		return size;
	    }

	    size = 0;
	    for (int i = 0; i < this.messages_.size(); i++) {
		size += com.google.protobuf.CodedOutputStream
			.computeMessageSize(1, this.messages_.get(i));
	    }
	    size += getUnknownFields().getSerializedSize();
	    this.memoizedSize = size;
	    return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
	    if (obj == this) {
		return true;
	    }
	    if (!(obj instanceof ProtobufMessage.SomeMessage other)) {
		return super.equals(obj);
	    }
	    if (!getMessagesList()
		    .equals(other.getMessagesList())) {
		return false;
	    }
	    if (!getUnknownFields().equals(other.getUnknownFields())) {
		return false;
	    }
	    return true;
	}

	@java.lang.Override
	public int hashCode() {
	    if (this.memoizedHashCode != 0) {
		return this.memoizedHashCode;
	    }
	    int hash = 41;
	    hash = (19 * hash) + SomeMessage.getDescriptor().hashCode();
	    if (getMessagesCount() > 0) {
		hash = (37 * hash) + SomeMessage.MESSAGES_FIELD_NUMBER;
		hash = (53 * hash) + getMessagesList().hashCode();
	    }
	    hash = (29 * hash) + getUnknownFields().hashCode();
	    this.memoizedHashCode = hash;
	    return hash;
	}

	public static ProtobufMessage.SomeMessage parseFrom(
		java.nio.ByteBuffer data)
		throws com.google.protobuf.InvalidProtocolBufferException {
	    return SomeMessage.PARSER.parseFrom(data);
	}

	public static ProtobufMessage.SomeMessage parseFrom(
		java.nio.ByteBuffer data,
		com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		throws com.google.protobuf.InvalidProtocolBufferException {
	    return SomeMessage.PARSER.parseFrom(data, extensionRegistry);
	}

	public static ProtobufMessage.SomeMessage parseFrom(
		com.google.protobuf.ByteString data)
		throws com.google.protobuf.InvalidProtocolBufferException {
	    return SomeMessage.PARSER.parseFrom(data);
	}

	public static ProtobufMessage.SomeMessage parseFrom(
		com.google.protobuf.ByteString data,
		com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		throws com.google.protobuf.InvalidProtocolBufferException {
	    return SomeMessage.PARSER.parseFrom(data, extensionRegistry);
	}

	public static ProtobufMessage.SomeMessage parseFrom(byte[] data)
		throws com.google.protobuf.InvalidProtocolBufferException {
	    return SomeMessage.PARSER.parseFrom(data);
	}

	public static ProtobufMessage.SomeMessage parseFrom(
		byte[] data,
		com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		throws com.google.protobuf.InvalidProtocolBufferException {
	    return SomeMessage.PARSER.parseFrom(data, extensionRegistry);
	}

	public static ProtobufMessage.SomeMessage parseFrom(java.io.InputStream input)
		throws java.io.IOException {
	    return com.google.protobuf.GeneratedMessage
		    .parseWithIOException(SomeMessage.PARSER, input);
	}

	public static ProtobufMessage.SomeMessage parseFrom(
		java.io.InputStream input,
		com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		throws java.io.IOException {
	    return com.google.protobuf.GeneratedMessage
		    .parseWithIOException(SomeMessage.PARSER, input, extensionRegistry);
	}

	public static ProtobufMessage.SomeMessage parseDelimitedFrom(java.io.InputStream input)
		throws java.io.IOException {
	    return com.google.protobuf.GeneratedMessage
		    .parseDelimitedWithIOException(SomeMessage.PARSER, input);
	}

	public static ProtobufMessage.SomeMessage parseDelimitedFrom(
		java.io.InputStream input,
		com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		throws java.io.IOException {
	    return com.google.protobuf.GeneratedMessage
		    .parseDelimitedWithIOException(SomeMessage.PARSER, input, extensionRegistry);
	}

	public static ProtobufMessage.SomeMessage parseFrom(
		com.google.protobuf.CodedInputStream input)
		throws java.io.IOException {
	    return com.google.protobuf.GeneratedMessage
		    .parseWithIOException(SomeMessage.PARSER, input);
	}

	public static ProtobufMessage.SomeMessage parseFrom(
		com.google.protobuf.CodedInputStream input,
		com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		throws java.io.IOException {
	    return com.google.protobuf.GeneratedMessage
		    .parseWithIOException(SomeMessage.PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
	    return SomeMessage.newBuilder();
	}

	public static Builder newBuilder() {
	    return SomeMessage.DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(ProtobufMessage.SomeMessage prototype) {
	    return SomeMessage.DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	@java.lang.Override
	public Builder toBuilder() {
	    return this == SomeMessage.DEFAULT_INSTANCE
		    ? new Builder()
		    : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(
		com.google.protobuf.GeneratedMessage.BuilderParent parent) {
	    Builder builder = new Builder(parent);
	    return builder;
	}

	/**
	 * Protobuf type {@code SomeMessage}
	 */
	public static final class Builder extends
		com.google.protobuf.GeneratedMessage.Builder<Builder> implements
		// @@protoc_insertion_point(builder_implements:SomeMessage)
		ProtobufMessage.SomeMessageOrBuilder {
	    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return ProtobufMessage.internal_static_SomeMessage_descriptor;
	    }

	    @java.lang.Override
	    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
		return ProtobufMessage.internal_static_SomeMessage_fieldAccessorTable
			.ensureFieldAccessorsInitialized(
							 ProtobufMessage.SomeMessage.class,
							 ProtobufMessage.SomeMessage.Builder.class);
	    }

	    // Construct using Sedapexpress.SomeMessage.newBuilder()
	    private Builder() {

	    }

	    private Builder(
		    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
		super(parent);

	    }

	    @java.lang.Override
	    public Builder clear() {
		super.clear();
		this.bitField0_ = 0;
		if (this.messagesBuilder_ == null) {
		    this.messages_ = java.util.Collections.emptyList();
		} else {
		    this.messages_ = null;
		    this.messagesBuilder_.clear();
		}
		this.bitField0_ = (this.bitField0_ & ~0x00000001);
		return this;
	    }

	    @java.lang.Override
	    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
		return ProtobufMessage.internal_static_SomeMessage_descriptor;
	    }

	    @java.lang.Override
	    public ProtobufMessage.SomeMessage getDefaultInstanceForType() {
		return ProtobufMessage.SomeMessage.getDefaultInstance();
	    }

	    @java.lang.Override
	    public ProtobufMessage.SomeMessage build() {
		ProtobufMessage.SomeMessage result = buildPartial();
		if (!result.isInitialized()) {
		    throw Builder.newUninitializedMessageException(result);
		}
		return result;
	    }

	    @java.lang.Override
	    public ProtobufMessage.SomeMessage buildPartial() {
		ProtobufMessage.SomeMessage result = new ProtobufMessage.SomeMessage(this);
		buildPartialRepeatedFields(result);
		if (this.bitField0_ != 0) {
		    buildPartial0(result);
		}
		onBuilt();
		return result;
	    }

	    private void buildPartialRepeatedFields(ProtobufMessage.SomeMessage result) {
		if (this.messagesBuilder_ == null) {
		    if (((this.bitField0_ & 0x00000001) != 0)) {
			this.messages_ = java.util.Collections.unmodifiableList(this.messages_);
			this.bitField0_ = (this.bitField0_ & ~0x00000001);
		    }
		    result.messages_ = this.messages_;
		} else {
		    result.messages_ = this.messagesBuilder_.build();
		}
	    }

	    private void buildPartial0(ProtobufMessage.SomeMessage result) {
		@SuppressWarnings("unused")
		int from_bitField0_ = this.bitField0_;
	    }

	    @java.lang.Override
	    public Builder mergeFrom(com.google.protobuf.Message other) {
		if (other instanceof ProtobufMessage.SomeMessage) {
		    return mergeFrom((ProtobufMessage.SomeMessage) other);
		} else {
		    super.mergeFrom(other);
		    return this;
		}
	    }

	    public Builder mergeFrom(ProtobufMessage.SomeMessage other) {
		if (other == ProtobufMessage.SomeMessage.getDefaultInstance()) {
		    return this;
		}
		if (this.messagesBuilder_ == null) {
		    if (!other.messages_.isEmpty()) {
			if (this.messages_.isEmpty()) {
			    this.messages_ = other.messages_;
			    this.bitField0_ = (this.bitField0_ & ~0x00000001);
			} else {
			    ensureMessagesIsMutable();
			    this.messages_.addAll(other.messages_);
			}
			onChanged();
		    }
		} else {
		    if (!other.messages_.isEmpty()) {
			if (this.messagesBuilder_.isEmpty()) {
			    this.messagesBuilder_.dispose();
			    this.messagesBuilder_ = null;
			    this.messages_ = other.messages_;
			    this.bitField0_ = (this.bitField0_ & ~0x00000001);
			    this.messagesBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getMessagesFieldBuilder() : null;
			} else {
			    this.messagesBuilder_.addAllMessages(other.messages_);
			}
		    }
		}
		this.mergeUnknownFields(other.getUnknownFields());
		onChanged();
		return this;
	    }

	    @java.lang.Override
	    public final boolean isInitialized() {
		return true;
	    }

	    @java.lang.Override
	    public Builder mergeFrom(
		    com.google.protobuf.CodedInputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
		if (extensionRegistry == null) {
		    throw new java.lang.NullPointerException();
		}
		try {
		    boolean done = false;
		    while (!done) {
			int tag = input.readTag();
			switch (tag) {
			case 0:
			    done = true;
			    break;
			case 10: {
			    ProtobufMessage.SomeMessage.Messages m = input
				    .readMessage(
						 ProtobufMessage.SomeMessage.Messages.parser(),
						 extensionRegistry);
			    if (this.messagesBuilder_ == null) {
				ensureMessagesIsMutable();
				this.messages_.add(m);
			    } else {
				this.messagesBuilder_.addMessage(m);
			    }
			    break;
			} // case 10
			default: {
			    if (!super.parseUnknownField(input, extensionRegistry, tag)) {
				done = true; // was an endgroup tag
			    }
			    break;
			} // default:
			} // switch (tag)
		    } // while (!done)
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
		    throw e.unwrapIOException();
		} finally {
		    onChanged();
		} // finally
		return this;
	    }

	    private int bitField0_;

	    private java.util.List<ProtobufMessage.SomeMessage.Messages> messages_ = java.util.Collections.emptyList();

	    private void ensureMessagesIsMutable() {
		if (!((this.bitField0_ & 0x00000001) != 0)) {
		    this.messages_ = new java.util.ArrayList<ProtobufMessage.SomeMessage.Messages>(this.messages_);
		    this.bitField0_ |= 0x00000001;
		}
	    }

	    private com.google.protobuf.RepeatedFieldBuilder<ProtobufMessage.SomeMessage.Messages, ProtobufMessage.SomeMessage.Messages.Builder, ProtobufMessage.SomeMessage.MessagesOrBuilder> messagesBuilder_;

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public java.util.List<ProtobufMessage.SomeMessage.Messages> getMessagesList() {
		if (this.messagesBuilder_ == null) {
		    return java.util.Collections.unmodifiableList(this.messages_);
		} else {
		    return this.messagesBuilder_.getMessageList();
		}
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public int getMessagesCount() {
		if (this.messagesBuilder_ == null) {
		    return this.messages_.size();
		} else {
		    return this.messagesBuilder_.getCount();
		}
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public ProtobufMessage.SomeMessage.Messages getMessages(int index) {
		if (this.messagesBuilder_ == null) {
		    return this.messages_.get(index);
		} else {
		    return this.messagesBuilder_.getMessage(index);
		}
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public Builder setMessages(
		    int index, ProtobufMessage.SomeMessage.Messages value) {
		if (this.messagesBuilder_ == null) {
		    if (value == null) {
			throw new NullPointerException();
		    }
		    ensureMessagesIsMutable();
		    this.messages_.set(index, value);
		    onChanged();
		} else {
		    this.messagesBuilder_.setMessage(index, value);
		}
		return this;
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public Builder setMessages(
		    int index, ProtobufMessage.SomeMessage.Messages.Builder builderForValue) {
		if (this.messagesBuilder_ == null) {
		    ensureMessagesIsMutable();
		    this.messages_.set(index, builderForValue.build());
		    onChanged();
		} else {
		    this.messagesBuilder_.setMessage(index, builderForValue.build());
		}
		return this;
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public Builder addMessages(ProtobufMessage.SomeMessage.Messages value) {
		if (this.messagesBuilder_ == null) {
		    if (value == null) {
			throw new NullPointerException();
		    }
		    ensureMessagesIsMutable();
		    this.messages_.add(value);
		    onChanged();
		} else {
		    this.messagesBuilder_.addMessage(value);
		}
		return this;
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public Builder addMessages(
		    int index, ProtobufMessage.SomeMessage.Messages value) {
		if (this.messagesBuilder_ == null) {
		    if (value == null) {
			throw new NullPointerException();
		    }
		    ensureMessagesIsMutable();
		    this.messages_.add(index, value);
		    onChanged();
		} else {
		    this.messagesBuilder_.addMessage(index, value);
		}
		return this;
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public Builder addMessages(
		    ProtobufMessage.SomeMessage.Messages.Builder builderForValue) {
		if (this.messagesBuilder_ == null) {
		    ensureMessagesIsMutable();
		    this.messages_.add(builderForValue.build());
		    onChanged();
		} else {
		    this.messagesBuilder_.addMessage(builderForValue.build());
		}
		return this;
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public Builder addMessages(
		    int index, ProtobufMessage.SomeMessage.Messages.Builder builderForValue) {
		if (this.messagesBuilder_ == null) {
		    ensureMessagesIsMutable();
		    this.messages_.add(index, builderForValue.build());
		    onChanged();
		} else {
		    this.messagesBuilder_.addMessage(index, builderForValue.build());
		}
		return this;
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public Builder addAllMessages(
		    java.lang.Iterable<? extends ProtobufMessage.SomeMessage.Messages> values) {
		if (this.messagesBuilder_ == null) {
		    ensureMessagesIsMutable();
		    com.google.protobuf.AbstractMessageLite.Builder
			    .addAll(
				    values,
				    this.messages_);
		    onChanged();
		} else {
		    this.messagesBuilder_.addAllMessages(values);
		}
		return this;
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public Builder clearMessages() {
		if (this.messagesBuilder_ == null) {
		    this.messages_ = java.util.Collections.emptyList();
		    this.bitField0_ = (this.bitField0_ & ~0x00000001);
		    onChanged();
		} else {
		    this.messagesBuilder_.clear();
		}
		return this;
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public Builder removeMessages(int index) {
		if (this.messagesBuilder_ == null) {
		    ensureMessagesIsMutable();
		    this.messages_.remove(index);
		    onChanged();
		} else {
		    this.messagesBuilder_.remove(index);
		}
		return this;
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public ProtobufMessage.SomeMessage.Messages.Builder getMessagesBuilder(
		    int index) {
		return getMessagesFieldBuilder().getBuilder(index);
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public ProtobufMessage.SomeMessage.MessagesOrBuilder getMessagesOrBuilder(
		    int index) {
		if (this.messagesBuilder_ == null) {
		    return this.messages_.get(index);
		} else {
		    return this.messagesBuilder_.getMessageOrBuilder(index);
		}
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public java.util.List<? extends ProtobufMessage.SomeMessage.MessagesOrBuilder> getMessagesOrBuilderList() {
		if (this.messagesBuilder_ != null) {
		    return this.messagesBuilder_.getMessageOrBuilderList();
		} else {
		    return java.util.Collections.unmodifiableList(this.messages_);
		}
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public ProtobufMessage.SomeMessage.Messages.Builder addMessagesBuilder() {
		return getMessagesFieldBuilder()
			.addBuilder(
				    ProtobufMessage.SomeMessage.Messages.getDefaultInstance());
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public ProtobufMessage.SomeMessage.Messages.Builder addMessagesBuilder(
		    int index) {
		return getMessagesFieldBuilder()
			.addBuilder(
				    index,
				    ProtobufMessage.SomeMessage.Messages.getDefaultInstance());
	    }

	    /**
	     * <code>repeated .SomeMessage.Messages messages = 1;</code>
	     */
	    public java.util.List<ProtobufMessage.SomeMessage.Messages.Builder> getMessagesBuilderList() {
		return getMessagesFieldBuilder().getBuilderList();
	    }

	    private com.google.protobuf.RepeatedFieldBuilder<ProtobufMessage.SomeMessage.Messages, ProtobufMessage.SomeMessage.Messages.Builder, ProtobufMessage.SomeMessage.MessagesOrBuilder> getMessagesFieldBuilder() {
		if (this.messagesBuilder_ == null) {
		    this.messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<ProtobufMessage.SomeMessage.Messages, ProtobufMessage.SomeMessage.Messages.Builder, ProtobufMessage.SomeMessage.MessagesOrBuilder>(
			    this.messages_,
			    ((this.bitField0_ & 0x00000001) != 0),
			    getParentForChildren(),
			    isClean());
		    this.messages_ = null;
		}
		return this.messagesBuilder_;
	    }

	    // @@protoc_insertion_point(builder_scope:SomeMessage)
	}

	// @@protoc_insertion_point(class_scope:SomeMessage)
	private static final ProtobufMessage.SomeMessage DEFAULT_INSTANCE;
	static {
	    DEFAULT_INSTANCE = new ProtobufMessage.SomeMessage();
	}

	public static ProtobufMessage.SomeMessage getDefaultInstance() {
	    return SomeMessage.DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<SomeMessage> PARSER = new com.google.protobuf.AbstractParser<SomeMessage>() {
	    @java.lang.Override
	    public SomeMessage parsePartialFrom(
		    com.google.protobuf.CodedInputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
		Builder builder = SomeMessage.newBuilder();
		try {
		    builder.mergeFrom(input, extensionRegistry);
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
		    throw e.setUnfinishedMessage(builder.buildPartial());
		} catch (com.google.protobuf.UninitializedMessageException e) {
		    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
		} catch (java.io.IOException e) {
		    throw new com.google.protobuf.InvalidProtocolBufferException(e)
			    .setUnfinishedMessage(builder.buildPartial());
		}
		return builder.buildPartial();
	    }
	};

	public static com.google.protobuf.Parser<SomeMessage> parser() {
	    return SomeMessage.PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<SomeMessage> getParserForType() {
	    return SomeMessage.PARSER;
	}

	@java.lang.Override
	public ProtobufMessage.SomeMessage getDefaultInstanceForType() {
	    return SomeMessage.DEFAULT_INSTANCE;
	}

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_SomeMessage_descriptor;
    private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_SomeMessage_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_SomeMessage_Messages_descriptor;
    private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_SomeMessage_Messages_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
	return ProtobufMessage.descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
	java.lang.String[] descriptorData = {
		"\n\022sedapexpress.proto\"S\n\013SomeMessage\022\'\n\010m" +
			"essages\030\001 \003(\0132\025.SomeMessage.Messages\032\033\n\010" +
			"Messages\022\017\n\007message\030\001 \001(\tb\006proto3"
	};
	ProtobufMessage.descriptor = com.google.protobuf.Descriptors.FileDescriptor
		.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {
						});
	internal_static_SomeMessage_descriptor = ProtobufMessage.getDescriptor().getMessageTypes().get(0);
	internal_static_SomeMessage_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
		ProtobufMessage.internal_static_SomeMessage_descriptor,
		new java.lang.String[] { "Messages", });
	internal_static_SomeMessage_Messages_descriptor = ProtobufMessage.internal_static_SomeMessage_descriptor.getNestedTypes().get(0);
	internal_static_SomeMessage_Messages_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
		ProtobufMessage.internal_static_SomeMessage_Messages_descriptor,
		new java.lang.String[] { "Message", });
	ProtobufMessage.descriptor.resolveAllFeaturesImmutable();
    }

// @@protoc_insertion_point(outer_class_scope)
}
